# Default values for zeebe-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: 
  elasticsearch:
    host: "vpc-ph1-dev-elk-new3my7xafqsg6oq3lxqluedey.ap-south-1.es.amazonaws.com"
    port: 443
    username: kibana
    password: Kibana@123
  zeebe: "{{ .Release.Name }}-zeebe"

image:
  repository: camunda/zeebe
  tag: 0.23.4
  pullPolicy: IfNotPresent

clusterSize: "1"
partitionCount: "1"
replicationFactor: "1"
cpuThreadCount: "2"
ioThreadCount: "2"
pvcSize: "10Gi"
pvcAccessModes: [ "ReadWriteOnce" ]
env: []

gateway:
  replicas: 1
  logLevel: warn
  env: []
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable:

elasticsearch:
  enabled: false
  imageTag: 6.8.5

kibana:
  enabled: false
  imageTag: 6.8.5

prometheus:
  enabled: false
  servicemonitor:
    enabled: false

JavaOpts: >-
  -XX:+UseParallelGC
  -XX:MinHeapFreeRatio=5
  -XX:MaxHeapFreeRatio=10
  -XX:MaxRAMPercentage=25.0
  -XX:GCTimeRatio=4
  -XX:AdaptiveSizePolicyWeight=90
  -XX:+PrintFlagsFinal
  -Xmx4g
  -Xms4g
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/usr/local/zeebe/data
  -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log

labels:
  app: zeebe    
serviceType: ClusterIP
serviceHttpPort: 9600
serviceGatewayPort: 26500    
serviceCommandPort: 26501     
serviceInternalPort: 26502  
resources: 
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 4Gi
probePath: /ready
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
podDisruptionBudget:
  enabled: false
  minAvailable:
  maxUnavailable: 1

nodeSelector: {}

tolerations: []

affinity: {}
