apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.global.zeebe . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ tpl .Values.global.zeebe . | quote }}
{{- toYaml  .Values.labels | nindent 4 }}
  annotations:
{{- toYaml  .Values.annotations | nindent 4 }}    
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.serviceHttpPort }}
      protocol: TCP
      name: {{ default "http" .Values.serviceHttpName  }}  
    - port: {{ .Values.serviceInternalPort }}
      protocol: TCP
      name: {{ default "internal" .Values.serviceInternalName  }}
    - port: {{ .Values.serviceCommandPort }}
      protocol: TCP
      name: {{ default "command" .Values.serviceCommandName }}
  selector:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ tpl .Values.global.zeebe . | quote }}
